INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:trying PoetryDB
INFO:poemtools:hello
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_author': 'list' object has no attribute 'join'
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 45, in get_author
    result = await asyncio.to_thread(requests.get(url+"/author/" + author + "/title"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Response' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 60, in get_author
    return f.format_list(authors)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 8, in format_list
    return result.join(", ")
           ^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'join'
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:trying PoetryDB
INFO:poemtools:hello
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:trying PoetryDB
INFO:poemtools:hello
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_author': can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 45, in get_author
    result = await asyncio.to_thread(requests.get(url+"/author/" + author + "/title"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Response' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 57, in get_author
    return ("There are multiple authors found in the database: " + f.format_list(authors) + ". Which one did you mean?")
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "list") to str
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:trying PoetryDB
ERROR:poemtools:
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 45, in get_author
    result = await asyncio.to_thread(requests.get(url+"/author/" + author + "/title"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Response' object is not callable
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:trying PoetryDB
ERROR:poemtools:
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 45, in get_author
    result = await asyncio.to_thread(requests.get(url+"/author/" + author + "/title"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'Response' object is not callable
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid author name: amy suo
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'become_thesaurus': Sampling not supported
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemprompts.py", line 19, in become_thesaurus
    response = await ctx.sample(prompt, system_prompt = sys, temperature = .75)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/server/context.py", line 232, in sample
    result: CreateMessageResult = await self.request_context.session.create_message(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/mcp/server/session.py", line 240, in create_message
    return await self.send_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/mcp/shared/session.py", line 297, in send_request
    raise McpError(response_or_error.error)
mcp.shared.exceptions.McpError: Sampling not supported
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'become_thesaurus': Sampling not supported
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemprompts.py", line 19, in become_thesaurus
    response = await ctx.sample(prompt, system_prompt = sys, temperature = .75)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/server/context.py", line 232, in sample
    result: CreateMessageResult = await self.request_context.session.create_message(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/mcp/server/session.py", line 240, in create_message
    return await self.send_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/mcp/shared/session.py", line 297, in send_request
    raise McpError(response_or_error.error)
mcp.shared.exceptions.McpError: Sampling not supported
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemprompts:Context()
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'become_thesaurus': Sampling not supported
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemprompts.py", line 22, in become_thesaurus
    response = await ctx.sample(prompt, system_prompt = sys, temperature = .75, model_preferences = "xLAM")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/server/context.py", line 232, in sample
    result: CreateMessageResult = await self.request_context.session.create_message(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/mcp/server/session.py", line 240, in create_message
    return await self.send_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/mcp/shared/session.py", line 297, in send_request
    raise McpError(response_or_error.error)
mcp.shared.exceptions.McpError: Sampling not supported
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemprompts:Context()
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'become_thesaurus': Sampling not supported
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemprompts.py", line 22, in become_thesaurus
    logger.info(ctx)
               ^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/server/context.py", line 232, in sample
    result: CreateMessageResult = await self.request_context.session.create_message(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/mcp/server/session.py", line 240, in create_message
    return await self.send_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/mcp/shared/session.py", line 297, in send_request
    raise McpError(response_or_error.error)
mcp.shared.exceptions.McpError: Sampling not supported
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_poem_title': can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 63, in get_poem_title
    return ("There are multiple authors found in the database: " + f.format_list(poe) + ". Which one did you mean?")
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "list") to str
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_poem_title': 0
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7096, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 63, in get_poem_title
    return ("There are multiple poems found in the database: " + f.format_list(poe[0]) + ". Which one did you mean?")
                                                                               ~~~^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4107, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3819, in get_loc
    raise KeyError(key) from err
KeyError: 0
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_poem_title': 0
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pandas/_libs/index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7096, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 65, in get_poem_title
    return f.format_entry(poe)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 12, in format_entry
    poem = {"Title": entry[0][0], "Poem": entry[1][0], "Poet": entry[2][0], "Tags": entry[3][0]}
                     ~~~~~^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/frame.py", line 4107, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3819, in get_loc
    raise KeyError(key) from err
KeyError: 0
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_poems_keyword': (sqlite3.OperationalError) no such column: Tag
[SQL: SELECT * FROM poemsf WHERE Poem LIKE "%bethlehem%" AND Poet LIKE "%yeats%" AND Tag LIKE "%%"]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: Tag

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 85, in get_poems_keyword
    poe = pd.read_sql_query("SELECT * FROM poemsf WHERE Poem LIKE \"%" + keyword + "%\" AND Poet LIKE \"%" + author + "%\" AND Tag LIKE \"%" + tag + "%\"", conn)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/io/sql.py", line 528, in read_sql_query
    return pandas_sql.read_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/io/sql.py", line 1848, in read_query
    result = self.execute(sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/io/sql.py", line 1671, in execute
    return self.con.exec_driver_sql(sql, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1775, in exec_driver_sql
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: Tag
[SQL: SELECT * FROM poemsf WHERE Poem LIKE "%bethlehem%" AND Poet LIKE "%yeats%" AND Tag LIKE "%%"]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_poems_keyword': zero-dimensional arrays cannot be concatenated
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 90, in get_poems_keyword
    return f.format_entries(poe)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 17, in format_entries
    poems = format_list(entries.apply(format_entry, axis = 1))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 7, in format_list
    result = np.concatenate(list.values).tolist()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-dimensional arrays cannot be concatenated
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_poems_keyword': zero-dimensional arrays cannot be concatenated
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 90, in get_poems_keyword
    return f.format_entries(poe)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 17, in format_entries
    poems = format_list(entries.apply(format_entry, axis = 1))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 7, in format_list
    result = np.concatenate(list.values).tolist()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-dimensional arrays cannot be concatenated
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_poems_keyword': The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 90, in get_poems_keyword
    return f.format_entries(poe)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 17, in format_entries
    if entries.count(0) > 1:
       ^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/generic.py", line 1577, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_tag': 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 218, in run
    result = type_adapter.validate_python(arguments)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 421, in validate_python
    return self.validator.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 152, in get_tag
    return f.format_entries(poe)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 18, in format_entries
    poems = (entries.apply(format_entry, axis = 1))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/frame.py", line 10381, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 12, in format_entry
    poem = {"Title": entry["Title"][0], "Poem": entry["Poem"][0], "Poet": entry["Poet"][0], "Tags": entry["Tags"][0]}
                                                ~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_tag': 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 218, in run
    result = type_adapter.validate_python(arguments)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 421, in validate_python
    return self.validator.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 152, in get_tag
    return f.format_entries(poe)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 18, in format_entries
    poems = (entries.apply(format_entry, axis = 1))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/frame.py", line 10381, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 12, in format_entry
    poem = {"Title": entry["Title"][0], "Poem": entry["Poem"][0], "Poet": entry["Poet"][0], "Tags": entry["Tags"][0]}
                                                ~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid author name: W.B. Yeats
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemprompts:Context()
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'become_thesaurus': Sampling not supported
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemprompts.py", line 25, in become_thesaurus
    response = await ctx.sample(prompt, system_prompt = sys, temperature = .75, model_preferences = "xLAM")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/server/context.py", line 232, in sample
    result: CreateMessageResult = await self.request_context.session.create_message(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/mcp/server/session.py", line 240, in create_message
    return await self.send_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/mcp/shared/session.py", line 297, in send_request
    raise McpError(response_or_error.error)
mcp.shared.exceptions.McpError: Sampling not supported
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemprompts:Context()
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'become_thesaurus': Sampling not supported
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemprompts.py", line 25, in become_thesaurus
    response = await ctx.sample(prompt, system_prompt = sys, temperature = .75, model_preferences = "xLAM")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/server/context.py", line 232, in sample
    result: CreateMessageResult = await self.request_context.session.create_message(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/mcp/server/session.py", line 240, in create_message
    return await self.send_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/mcp/shared/session.py", line 297, in send_request
    raise McpError(response_or_error.error)
mcp.shared.exceptions.McpError: Sampling not supported
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_reference': 0
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 413, in get_loc
    return self._range.index(new_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 168, in get_reference
    result += f.format_entries(poe)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 25, in format_entries
    return format_entry(entries)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 12, in format_entry
    poem = {"Title": entry["Title"][0], "Poem": entry["Poem"][0], "Poet": entry["Poet"][0], "Tags": entry["Tags"][0]}
                     ~~~~~~~~~~~~~~^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/series.py", line 1130, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/series.py", line 1246, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 415, in get_loc
    raise KeyError(key) from err
KeyError: 0
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_reference': 0
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 413, in get_loc
    return self._range.index(new_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 168, in get_reference
    result += f.format_entries(poe)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 25, in format_entries
    return format_entry(entries)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 12, in format_entry
    poem = {"Title": entry["Title"][0], "Poem": entry["Poem"][0], "Poet": entry["Poet"][0], "Tags": entry["Tags"][0]}
                     ~~~~~~~~~~~~~~^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/series.py", line 1130, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/series.py", line 1246, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 415, in get_loc
    raise KeyError(key) from err
KeyError: 0
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Tower
NoneType: None
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Tower
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Tower
NoneType: None
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Tower
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'streamable-http' on http://127.0.0.1:8004/mcp
INFO:mcp.server.streamable_http_manager:StreamableHTTP session manager started
INFO:mcp.server.streamable_http_manager:Created new transport with session ID: 2cebddf9f83b4555958778b396dc47ca
INFO:mcp.server.streamable_http_manager:Created new transport with session ID: 4cc19a832eee449bb12d54924eadb691
INFO:mcp.server.streamable_http_manager:Created new transport with session ID: a191f34daef242ae94c8e7d72497df65
INFO:mcp.server.streamable_http_manager:Created new transport with session ID: fbbce178dda14f79ab5ba6eecd03fcff
INFO:mcp.server.streamable_http_manager:Created new transport with session ID: a7745e6a59d846e484441a0af041a60b
INFO:mcp.server.streamable_http_manager:StreamableHTTP session manager shutting down
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'streamable-http' on http://127.0.0.1:8004/mcp
INFO:mcp.server.streamable_http_manager:StreamableHTTP session manager started
INFO:mcp.server.streamable_http_manager:Created new transport with session ID: 35fe6cf9b75e40908cbdfa5e835674c6
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.streamable_http_manager:StreamableHTTP session manager shutting down
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'streamable-http' on http://127.0.0.1:8004/mcp
INFO:mcp.server.streamable_http_manager:StreamableHTTP session manager started
INFO:mcp.server.streamable_http_manager:Created new transport with session ID: 355b4a8c43944d81bb0fc03f01d27b99
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_author': zero-dimensional arrays cannot be concatenated
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 53, in get_author
    ctx.info(f"Related tags for {authors["Poet"][0]}: {f.format_tags(f.format_list(authors["Tags"]))}")
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 7, in format_list
    result = np.concatenate(list.values).tolist()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-dimensional arrays cannot be concatenated
INFO:mcp.server.lowlevel.server:Warning: RuntimeWarning: coroutine 'Context.info' was never awaited
INFO:mcp.server.streamable_http_manager:StreamableHTTP session manager shutting down
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'streamable-http' on http://127.0.0.1:8004/mcp
INFO:mcp.server.streamable_http_manager:StreamableHTTP session manager started
INFO:mcp.server.streamable_http_manager:StreamableHTTP session manager shutting down
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_poem_title': zero-dimensional arrays cannot be concatenated
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 71, in get_poem_title
    return ("There are multiple poems found in the database: " + f.format_list(poe["Title"]) + ". Which one did you mean?")
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 7, in format_list
    result = np.concatenate(list.values).tolist()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-dimensional arrays cannot be concatenated
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_poem_title': zero-dimensional arrays cannot be concatenated
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 71, in get_poem_title
    return ("There are multiple poems found in the database: " + f.format_list(poe["Title"]) + ". Which one did you mean?")
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 7, in format_list
    result = np.concatenate(list.values).tolist()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-dimensional arrays cannot be concatenated
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_author': zero-dimensional arrays cannot be concatenated
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 54, in get_author
    return f.format_list(authors["Title"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 7, in format_list
    result = np.concatenate(list.values).tolist()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-dimensional arrays cannot be concatenated
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_author': zero-dimensional arrays cannot be concatenated
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 57, in get_author
    return f.format_list(authors["Title"])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/format.py", line 7, in format_list
    result = np.concatenate(list.values).tolist()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-dimensional arrays cannot be concatenated
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Lake Isle of Innisfree
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Lake Isle of Innisfree
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Lake Isle of Innisfree
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Lake Isle of Innisfree
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Lake Isle of Innisfree
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Lake Isle of Innisfree
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Lake Isle of Innisfree
NoneType: None
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Lake Isle of Innisfree
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Sorrow of Love
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Second Coming
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: To a Friend Whose Work Has Come to Nothing
NoneType: None
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: random
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Lake Isle of Innisfree
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Second Coming
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: Sailing to Byzantium
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: Easter, 1916
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Tower
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: Byzantium
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: Under Ben Bulben
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Circus Animals' Desertion
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Second Coming
NoneType: None
INFO:poemtools:returned: Empty DataFrame
Columns: [index, Title, Poem, Poet, Tags]
Index: []
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid poem name: The Second Coming
NoneType: None
INFO:poemtools:returned: Empty DataFrame
Columns: [index, Title, Poem, Poet, Tags]
Index: []
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_tag': read_sql_query() missing 1 required positional argument: 'con'
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 218, in run
    result = type_adapter.validate_python(arguments)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 421, in validate_python
    return self.validator.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 198, in get_tag
    all = pd.read_sql_query(f"SELECT DISTINCT Poet FROM poemsf WHERE Tags LIKE \"%{tag}%\"")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: read_sql_query() missing 1 required positional argument: 'con'
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_tag': read_sql_query() missing 1 required positional argument: 'con'
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 218, in run
    result = type_adapter.validate_python(arguments)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 421, in validate_python
    return self.validator.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 198, in get_tag
    all = pd.read_sql_query(f"SELECT DISTINCT Poet FROM poemsf WHERE Tags LIKE \"%{tag}%\"")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: read_sql_query() missing 1 required positional argument: 'con'
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation cannot find any poems under tag 'mental illness'
NoneType: None
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_tag': 
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 218, in run
    result = type_adapter.validate_python(arguments)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 421, in validate_python
    return self.validator.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 218, in get_tag
    raise Exception
Exception
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation cannot find any poems under tag 'death'
NoneType: None
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_tag': 
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 218, in run
    result = type_adapter.validate_python(arguments)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 421, in validate_python
    return self.validator.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 218, in get_tag
    raise Exception
Exception
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation cannot find any poems under tag 'nature'
NoneType: None
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_tag': 
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 218, in run
    result = type_adapter.validate_python(arguments)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pydantic/type_adapter.py", line 421, in validate_python
    return self.validator.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 218, in get_tag
    raise Exception
Exception
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_reference': cannot access local variable 'tag' where it is not associated with a value
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 238, in get_reference
    tag += sql + "(Tags LIKE \"%"
    ^^^
UnboundLocalError: cannot access local variable 'tag' where it is not associated with a value
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:poemtools:poetry foundation invalid author name:  Woolf
NoneType: None
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_author': can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 51, in get_author
    return ("There are multiple authors found in the database: " + f.format_list(authors) + ". Which one did you mean?")
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "list") to str
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_author': can only concatenate str (not "list") to str
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 51, in get_author
    return ("There are multiple authors found in the database: " + f.format_list(authors) + ". Which one did you mean?")
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "list") to str
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_reference': cannot access local variable 'tag' where it is not associated with a value
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 238, in get_reference
    tag += sql + "(Tags LIKE \"%"
    ^^^
UnboundLocalError: cannot access local variable 'tag' where it is not associated with a value
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_reference': cannot access local variable 'tag' where it is not associated with a value
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 238, in get_reference
    tag += sql + "(Tags LIKE \"%"
    ^^^
UnboundLocalError: cannot access local variable 'tag' where it is not associated with a value
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_reference': cannot access local variable 'tag' where it is not associated with a value
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 238, in get_reference
    tag += sql + "(Tags LIKE \"%"
    ^^^
UnboundLocalError: cannot access local variable 'tag' where it is not associated with a value
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_reference': cannot access local variable 'tag' where it is not associated with a value
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 238, in get_reference
    tag += sql + "(Tags LIKE \"%"
    ^^^
UnboundLocalError: cannot access local variable 'tag' where it is not associated with a value
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_reference': (sqlite3.OperationalError) near ")": syntax error
[SQL: SELECT * FROM poemsf WHERE (Tags LIKE "%Mental Health and Illness%" OR Tags LIKE "%Relationships and Family%" OR Tags LIKE "%Love and Sexuality%" OR Tags LIKE "%Nature and the Environment%" OR Tags LIKE "%Death and Mortality%" OR Tags LIKE "%Identity and Selfhood%" OR Tags LIKE "%Social Commentaries"%) ]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near ")": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 242, in get_reference
    poe = pd.read_sql_query(tag, conn)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/io/sql.py", line 528, in read_sql_query
    return pandas_sql.read_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/io/sql.py", line 1848, in read_query
    result = self.execute(sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/pandas/io/sql.py", line 1671, in execute
    return self.con.exec_driver_sql(sql, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1775, in exec_driver_sql
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2351, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 943, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near ")": syntax error
[SQL: SELECT * FROM poemsf WHERE (Tags LIKE "%Mental Health and Illness%" OR Tags LIKE "%Relationships and Family%" OR Tags LIKE "%Love and Sexuality%" OR Tags LIKE "%Nature and the Environment%" OR Tags LIKE "%Death and Mortality%" OR Tags LIKE "%Identity and Selfhood%" OR Tags LIKE "%Social Commentaries"%) ]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemprompts:Context()
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:openai._base_client:Retrying request to /models in 0.456174 seconds
INFO:openai._base_client:Retrying request to /models in 0.771588 seconds
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
ERROR:FastMCP.fastmcp.tools.tool_manager:Error calling tool 'get_poem_title': name 'poem' is not defined
Traceback (most recent call last):
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool_manager.py", line 130, in call_tool
    return await tool.run(arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/.venv/lib/python3.12/site-packages/fastmcp/tools/tool.py", line 220, in run
    result = await result
             ^^^^^^^^^^^^
  File "/home/amysuo12/amd2025test/mcp/poemtools.py", line 97, in get_poem_title
    logger.exception(f"poetry foundation invalid poem name: {poem}")
                                                             ^^^^
NameError: name 'poem' is not defined. Did you mean: 'poe'?
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:httpx:HTTP Request: POST http://10.194.176.195/v1/chat/completions "HTTP/1.1 200 OK"
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:httpx:HTTP Request: POST http://localhost:8001/v1/chat/completions "HTTP/1.1 200 OK"
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:httpx:HTTP Request: POST http://localhost:8001/v1/chat/completions "HTTP/1.1 200 OK"
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:httpx:HTTP Request: POST http://localhost:8001/v1/chat/completions "HTTP/1.1 200 OK"
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:httpx:HTTP Request: POST http://localhost:8001/v1/chat/completions "HTTP/1.1 200 OK"
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:httpx:HTTP Request: POST http://localhost:8001/v1/chat/completions "HTTP/1.1 200 OK"
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:httpx:HTTP Request: POST http://localhost:8001/v1/chat/completions "HTTP/1.1 200 OK"
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:httpx:HTTP Request: POST http://localhost:8001/v1/chat/completions "HTTP/1.1 200 OK"
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:httpx:HTTP Request: POST http://localhost:8001/v1/chat/completions "HTTP/1.1 200 OK"
INFO:mcp.server.lowlevel.server:Processing request of type CallToolRequest
INFO:httpx:HTTP Request: POST http://localhost:8001/v1/chat/completions "HTTP/1.1 200 OK"
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
INFO:poemtools:setup started
INFO:poemtools:setup ended
INFO:FastMCP.fastmcp.server.server:Starting MCP server 'poetry server' with transport 'stdio'
INFO:mcp.server.lowlevel.server:Processing request of type ListToolsRequest
